### ISSUE TITLE
Unsupported Accept header should result in 406

### ISSUE THREAD

**Issue by nbarbettini** [stormpath/stormpath-framework-tck#217]
The `/oauth/token` endpoint should strictly only allow `Accept: application/json` requests, and return HTTP 406 on anything else.

**Comment by edjiang** [comment]
Please see my comment here: https://github.com/stormpath/stormpath-framework-tck/pull/218#issuecomment-203087653

**Comment by robertjd** [comment]
I'm with @edjiang on this one.  The response will always be JSON, so there's really no point in asserting the Accept header.

**Comment by nbarbettini** [comment]
I will bow to @edjiang and @robertjd on this one. :smile: 

I assume that #16 is okay, though?

**Comment by edjiang** [comment]
Yeah, that's fine. Although my specific bias is not to write unnecessary tests, and that behavior really isn't necessary for things to function...
