### ISSUE TITLE
Login with Facebook

### ISSUE THREAD

**Issue by edjiang** [stormpath/stormpath-framework-tck#221]
We should be able to login with a social provider. Since this endpoint forwards it to Stormpath, @nbarbettini and I figured that the best chance right now to deal with the chaos is just to test the things we can test. 

There's a fairly straightforward way to test Facebook right now, so I'm going to build a test that logs in with Facebook, and use that for now.

**Comment by nbarbettini** [comment]
:+1: 

I'd suggest renaming this "Login with Facebook" because that's specifically what you'll be testing.
