### ISSUE TITLE
SocialLoginIT prevents ALL tests from being run

### ISSUE THREAD

**Issue by bretterer** [stormpath/stormpath-framework-tck#229]
@edjiang your socialLoginIT test prevents all tests from being run.   Not sure what is going on here, but the only way I could get ANY of my IT's to run, I had to remove the SocialLoginIT.

**Comment by edjiang** [comment]
Huh, can you please provide instructions on how to reproduce, and a screenshot of the test results / console output?

The only thing I can think of is that you need a FB directory mapped to your test application, as it will grab your FB API key and generate a FB test user. @nbarbettini are you experiencing the same issues with teh Social Login IT? 

Here's me running against Laravel: 

![screen shot 2016-04-01 at 9 05 17 am](https://cloud.githubusercontent.com/assets/918770/14212679/df100a16-f7e8-11e5-984b-7ad262126f6b.png)

**Comment by edjiang** [comment]
Oh, also, with the social login ITs, we added the requirement to have the `STORMPATH_APPLICATION_HREF` env variable set. You can probably find the error in the stack trace in the console output.

**Comment by nbarbettini** [comment]
When I run the whole suite, SocialLoginITs fails (expected, because my integration doesn't support it yet). But it doesn't prevent the rest of the tests from running. Weird.

**Comment by nbarbettini** [comment]
Scratch that, I saw this behavior today.

I think it's a bug in testng: http://stackoverflow.com/questions/31476604/testng-all-subsequent-test-classes-are-skipped-when-beforeclass-method-fails

**Comment by nbarbettini** [comment]
I think I fixed it in abde66c. @bretterer, can you try again?
