### ISSUE TITLE
If the password doesn't meet password requirements, we need to re-render the form.

### ISSUE THREAD

**Issue by edjiang** [stormpath/stormpath-framework-tck#247]
https://github.com/stormpath/stormpath-framework-spec/blob/master/password-reset.md#post-handling

> If the error is a password policy validation error, re-render the change password form and display the error to the user

**Comment by nbarbettini** [comment]
Is this a dupe of #157?

**Comment by edjiang** [comment]
Yes, couldn't find that earlier for some reason. Sorry!

**Comment by nbarbettini** [comment]
Not a problem, there's a lot of issues :smile: 

FYI, I tagged the first stage (`/forgot`) as `forgot-password`, and the second change (`/change`) as `change-password`).

**Comment by edjiang** [comment]
That's probably why
