### ISSUE TITLE
Support Absolute hrefs for Location Header

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-framework-tck#257]
Damir ran into a problem with rails, which uses absolute values for location header:

> I've been working on some issues with the Logout today. I've got the TCK failing on the redirect spec, saying:
> 
> Expected header "Location" was not is "/", was "http://localhost:8080/". Headers are: 
> 
> The difference is that Rails is by default returning the absolute path on redirects, and you guys are expecting relatives. Actually, I'm having a hard time forcing it to send out relative paths.

I see in the some of the IT tests that it is checking the relative path.  Anything we can do about this?

**Comment by nbarbettini** [comment]
I can work on this late in the week, unless @edjiang can look at it sooner.

**Comment by DamirSvrtan** [comment]
Please ping me once this is done.

**Comment by omgitstom** [comment]
@nbarbettini @edjiang 

@DamirSvrtan still needs resolution on this

**Comment by edjiang** [comment]
I can get on this tomorrow.

**Comment by edjiang** [comment]
Acknowledging that I did not get this today, but I will get this tomorrow.
