### ISSUE TITLE
Incorporate latest changes for Framework Spec 1.0

### ISSUE THREAD

**Issue by edjiang** [stormpath/stormpath-framework-tck#276]
- [x] https://github.com/stormpath/stormpath-framework-spec/pull/87
- [x] https://github.com/stormpath/stormpath-framework-spec/pull/94
- [x] https://github.com/stormpath/stormpath-framework-spec/pull/100
- [x] https://github.com/stormpath/stormpath-framework-spec/pull/101
- [x] https://github.com/stormpath/stormpath-framework-spec/pull/76
- [x] https://github.com/stormpath/stormpath-framework-spec/pull/77
- [x] https://github.com/stormpath/stormpath-framework-spec/pull/102
- [x] https://github.com/stormpath/stormpath-framework-spec/pull/103
- [x] https://github.com/stormpath/stormpath-framework-spec/pull/106
- [x] https://github.com/stormpath/stormpath-framework-spec/pull/107
- [x] https://github.com/stormpath/stormpath-framework-spec/pull/105
- [x] https://github.com/stormpath/stormpath-framework-spec/pull/104

**Comment by omgitstom** [comment]
thank you @edjiang !

**Comment by edjiang** [comment]
I went through these changes, and spawned #277 #278 #279 #280 #281.

Closing this issue.
