### ISSUE TITLE
Oauth2IT#oauthClientCredentialsGrantFailsWithoutAPISecret not conforming to the spec.

### ISSUE THREAD

**Issue by DamirSvrtan** [stormpath/stormpath-framework-tck#285]
I've got two issues with this spec:
- If someone tries to submit a client credentials oauth2 request with an invalid secret, the spec expects the response status to be 401. However, the Stormpath API returns a 400 status (check the image below). Shouldn't we just be forwarding status data from api.stormpath.com? 

<img width="748" alt="screen shot 2016-07-12 at 16 45 11" src="https://cloud.githubusercontent.com/assets/1437202/16771258/1bc33804-4850-11e6-9b55-a53c6819feeb.png">
- The same tck acceptance spec expects to get an error message containing: 'invalid_client'. However the stormpath-framework-spec says that we should return 'invalid_request' as the error in json: https://github.com/stormpath/stormpath-framework-spec/blob/master/oauth2.md#error-transformations

@nbarbettini @omgitstom @edjiang am I doing something wrong here? Thnx!

**Comment by edjiang** [comment]
Yeah, I'm running into this myself as well. I need to review the tests today, but @nbarbettini and I took a look at the spec and wrote tests compliant to the OAuth spec. Our implementation of Client Credentials in our REST API is a bit weird, so we may have to transform those errors.

**Comment by edjiang** [comment]
In response to your bullets:
1. The test is correct. OAuth allows you to designate a client authentication scheme. For our integrations, we're using Basic Auth for client credentials. For the main REST API, it's POST body parameters. In this case, you need to transform the error. 
2. This is also correct. The thing you linked is just an example.

**Comment by DamirSvrtan** [comment]
@edjiang so the TCK is correct, and I should make the Rails framework integration comply to it? 

No problem, doing it right now :)

**Comment by edjiang** [comment]
Yes, although `oauthErrorsOnUnsupportedGrantTypes` will still fail if you pass things through. I filed something in Jira about it.

I think the bigger question here is whether or not passing through is a valid implementation strategy...

**Comment by edjiang** [comment]
Same thing for `oauthClientCredentialsGrantSucceeds`; it's in jira now

**Comment by DamirSvrtan** [comment]
@edjiang I've modified the Rails code to conform to the tck spec, when it changes feel free to ping me if there's something I should change. Thnx for the quick responses, closing this.
